package game;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;
import javax.faces.application.FacesMessage;
import java.util.ResourceBundle;

public class NumberBean {

	Integer userNumber; // user entered number 
	int randomNumber ;  // random number generated by application
	int count;

	public NumberBean () {
		randomNumber = (int)(Math.random()*20);
		count = 0;
		System.out.println( "Random number: " + randomNumber + ", count:" + count);
	}
	
	public void setUserNumber (Integer value){
		this.userNumber = value;
	}
  
	public Integer getUserNumber () {
		return this.userNumber;
	} 
	
	
	public String playagain () {
		FacesContext context = FacesContext.getCurrentInstance();
		HttpSession session = (HttpSession) context.getExternalContext().getSession(false);
		session.invalidate();
		return "playagain"; 
	}
  
	public String checkGuess () {
		// if guessed, return 'success' for navigation
		System.out.println ("count: " + count);
		if (count == 5)
			return "";
		count++;
		
		
    	if ( userNumber.intValue() == randomNumber ) {
    		return "success";
    	}
    	else {
    		// get a reference to properties file to retreive messages
    		FacesContext context = FacesContext.getCurrentInstance();
    		ResourceBundle bundle = ResourceBundle.getBundle("game.messages",
                    		context.getViewRoot().getLocale());	
    		// if number bigger, get appropriate message
    		String msg = "";
    		if (count == 5) {
    			System.out.println("***");
    			msg = bundle.getString("stop_play");
    		}
    		else if (userNumber.intValue() > randomNumber ) 
    			msg = bundle.getString("tryagain_smaller");
    		else // if number smaller, get appropriate message
    			msg = bundle.getString("tryagain_bigger");
      
    		// add message to be displayed on the page via <h:messages> tag
    		context.addMessage (null, new FacesMessage(msg)); 

    		// return null for navigation to display the same page
    		return null;
    	}
	}
}